/* ============================================================
   LLM-converted feat entries (bulk pass over data/feats.json) — see
   effects/tools/conversion-guide.md for the schema and process, and
   effects/db/handwritten.js for the hand-authored proof-of-schema entries
   this batch complements (duplicates of those, e.g. Alert/Tough/Resilient/
   Sharpshooter, were dropped here in favor of the hand-authored version).
   Generated by 8 parallel Haiku 4.5 conversion passes, then merged and
   checked with effects/tools/validate-db.js. `uses` blocks (limited-use
   trackers) were added afterward by effects/tools/generate-uses.js, a
   deterministic scan for explicit finite-use + recharge phrasings — see
   its header comment for what it does and doesn't catch.
   ============================================================ */
registerEffects({
  "feat|aberrant dragonmark": {
    "name": "Aberrant Dragonmark",
    "sv": 1,
    "unsupported": [
      {
        "reason": "spell learning, Hit Dice resource expenditure, random flaw, DM adjudication",
        "tags": [
          "spell",
          "resource",
          "random"
        ]
      }
    ]
  },
  "feat|adept of the black robes": {
    "name": "Adept of the Black Robes",
    "sv": 1,
    "unsupported": [
      {
        "reason": "spell learning, Hit Dice resource expenditure for damage boost",
        "tags": [
          "spell",
          "resource"
        ]
      }
    ]
  },
  "feat|adept of the red robes": {
    "name": "Adept of the Red Robes",
    "sv": 1,
    "unsupported": [
      {
        "reason": "d20 roll modification (treat low rolls as 10), proficiency-limited resource",
        "tags": [
          "d20-mod",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|adept of the white robes": {
    "name": "Adept of the White Robes",
    "sv": 1,
    "unsupported": [
      {
        "reason": "spell learning, reaction economy, spell slot expenditure for variable damage reduction",
        "tags": [
          "spell",
          "reaction",
          "resource"
        ]
      }
    ]
  },
  "feat|agent of order": {
    "name": "Agent of Order",
    "sv": 1,
    "unsupported": [
      {
        "reason": "attack-dependent extra damage, saving throw mechanism, proficiency-limited resource",
        "tags": [
          "attack",
          "save",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|baleful scion": {
    "name": "Baleful Scion",
    "sv": 1,
    "unsupported": [
      {
        "reason": "attack-dependent extra damage, healing mechanic, proficiency-limited resource",
        "tags": [
          "attack",
          "healing",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|bountiful luck": {
    "name": "Bountiful Luck",
    "sv": 1,
    "unsupported": [
      {
        "reason": "post-hoc reroll of ally's d20, reaction economy, proficiency-limited resource",
        "tags": [
          "reroll",
          "reaction",
          "resource"
        ]
      }
    ]
  },
  "feat|charger": {
    "name": "Charger",
    "sv": 1,
    "unsupported": [
      {
        "reason": "action economy (Dash + bonus action), attack-dependent damage and movement",
        "tags": [
          "action",
          "attack",
          "movement"
        ]
      }
    ]
  },
  "feat|dungeon delver": {
    "name": "Dungeon Delver",
    "sv": 1,
    "effects": [
      {
        "target": "skill-perception",
        "op": "adv"
      },
      {
        "target": "skill-investigation",
        "op": "adv"
      }
    ],
    "unsupported": [
      {
        "reason": "advantage on trap saves and trap damage resistance not modeled",
        "tags": [
          "trap-save",
          "damage-resistance"
        ]
      }
    ]
  },
  "feat|cohort of chaos": {
    "name": "Cohort of Chaos",
    "sv": 1,
    "unsupported": [
      {
        "reason": "d4 roll table triggered by d20 result; no roll-table model",
        "tags": [
          "roll-table",
          "resource"
        ]
      }
    ]
  },
  "feat|crossbow expert": {
    "name": "Crossbow Expert",
    "sv": 1,
    "unsupported": [
      {
        "reason": "weapon loading, close-range effects, and bonus-action attacks not modeled",
        "tags": [
          "weapons",
          "bonus-action"
        ]
      }
    ]
  },
  "feat|crusher": {
    "name": "Crusher",
    "sv": 1,
    "unsupported": [
      {
        "reason": "attack trigger (movement on hit) and conditional advantage require attack tracking",
        "tags": [
          "attack-tracking",
          "conditional-advantage"
        ]
      }
    ]
  },
  "feat|defensive duelist": {
    "name": "Defensive Duelist",
    "sv": 1,
    "unsupported": [
      {
        "reason": "AC modification via reaction not modeled",
        "tags": [
          "ac",
          "reaction"
        ]
      }
    ]
  },
  "feat|dragon fear": {
    "name": "Dragon Fear",
    "sv": 1,
    "unsupported": [
      {
        "reason": "breath-weapon variant action not modeled",
        "tags": [
          "breath-weapon",
          "action"
        ]
      }
    ]
  },
  "feat|dragon hide": {
    "name": "Dragon Hide",
    "sv": 1,
    "unsupported": [
      {
        "reason": "AC calculation and natural-weapon attacks not modeled",
        "tags": [
          "ac",
          "natural-weapon"
        ]
      }
    ]
  },
  "feat|dual wielder": {
    "name": "Dual Wielder",
    "sv": 1,
    "unsupported": [
      {
        "reason": "AC modification and weapon-property effects not modeled",
        "tags": [
          "ac",
          "weapon-property"
        ]
      }
    ]
  },
  "feat|durable": {
    "name": "Durable",
    "sv": 1,
    "unsupported": [
      {
        "reason": "hit-die roll minimum not modeled",
        "tags": [
          "hit-die",
          "roll-tracking"
        ]
      }
    ]
  },
  "feat|dwarven fortitude": {
    "name": "Dwarven Fortitude",
    "sv": 1,
    "unsupported": [
      {
        "reason": "hit-die spending tied to action not modeled",
        "tags": [
          "hit-die",
          "action-tie"
        ]
      }
    ]
  },
  "feat|elemental adept": {
    "name": "Elemental Adept",
    "sv": 1,
    "unsupported": [
      {
        "reason": "damage-die minimum and damage-resistance effects not modeled",
        "tags": [
          "damage",
          "resistance"
        ]
      }
    ]
  },
  "feat|elven accuracy": {
    "name": "Elven Accuracy",
    "sv": 1,
    "unsupported": [
      {
        "reason": "reroll one die when you have advantage on attack using DEX/INT/WIS/CHA",
        "tags": [
          "reroll"
        ]
      }
    ]
  },
  "feat|ember of the fire giant": {
    "name": "Ember of the Fire Giant",
    "sv": 1,
    "unsupported": [
      {
        "reason": "bonus action aura damage with save DC and resource tracking",
        "tags": [
          "resource",
          "damage"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|fade away": {
    "name": "Fade Away",
    "sv": 1,
    "unsupported": [
      {
        "reason": "reaction-triggered invisibility with per-rest usage tracking",
        "tags": [
          "reaction",
          "resource"
        ]
      }
    ]
  },
  "feat|fey touched": {
    "name": "Fey Touched",
    "sv": 1,
    "choices": [
      { "id": "feySpell", "kind": "spellfilter", "filter": "level=1|school=E;D", "label": "Choose a 1st-level divination/enchantment spell" }
    ],
    "effects": [
      { "target": "spell-grant", "op": "grant-free", "value": { "name": "misty step" } },
      { "target": "spell-grant", "op": "grant-free", "value": { "name": "{choice:feySpell}" }, "activation": { "kind": "choice", "choice": "feySpell" } }
    ],
    "unsupported": [
      {
        "reason": "each spell can also be cast once without a slot, recharging on a long rest — at-will/daily casting not modeled here",
        "tags": ["spellcasting", "resource"]
      }
    ]
  },
  "feat|fighting initiate": {
    "name": "Fighting Initiate",
    "sv": 1,
    "unsupported": [
      {
        "reason": "fighting style selection not modeled in effects engine",
        "tags": []
      }
    ]
  },
  "feat|flames of phlegethos": {
    "name": "Flames of Phlegethos",
    "sv": 1,
    "unsupported": [
      {
        "reason": "fire damage die reroll and conditional melee reaction damage",
        "tags": [
          "reroll",
          "resource"
        ]
      }
    ]
  },
  "feat|fury of the frost giant": {
    "name": "Fury of the Frost Giant",
    "sv": 1,
    "unsupported": [
      {
        "reason": "retaliatory save DC and damage on hit with resource tracking",
        "tags": [
          "resource",
          "damage"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|gift of the chromatic dragon": {
    "name": "Gift of the Chromatic Dragon",
    "sv": 1,
    "unsupported": [
      {
        "reason": "bonus action weapon infusion and reactive resistance with resource tracking",
        "tags": [
          "resource",
          "damage"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|gift of the gem dragon": {
    "name": "Gift of the Gem Dragon",
    "sv": 1,
    "unsupported": [
      {
        "reason": "telekinetic reprisal save DC and damage on trigger with resource tracking",
        "tags": [
          "resource",
          "damage"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|gift of the metallic dragon": {
    "name": "Gift of the Metallic Dragon",
    "sv": 1,
    "unsupported": [
      {
        "reason": "at-will/daily innate casting of cure wounds (no slot involved), plus protective wings AC bonus reaction with resource tracking",
        "tags": [
          "spell",
          "reaction",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|grappler": {
    "name": "Grappler",
    "sv": 1,
    "unsupported": [
      {
        "reason": "condition-dependent attack advantage and grapple-check pinning action",
        "tags": [
          "advantage",
          "condition"
        ]
      }
    ]
  },
  "feat|great weapon master": {
    "name": "Great Weapon Master",
    "sv": 1,
    "effects": [
      {
        "target": "attack-hit",
        "op": "add",
        "value": -5,
        "activation": {
          "kind": "toggle",
          "id": "gwm",
          "label": "Great Weapon Master −5/+10",
          "default": false
        }
      },
      {
        "target": "damage-bonus",
        "op": "add",
        "value": 10,
        "activation": {
          "kind": "toggle",
          "id": "gwm",
          "label": "Great Weapon Master −5/+10",
          "default": false
        }
      }
    ]
  },
  "feat|guile of the cloud giant": {
    "name": "Guile of the Cloud Giant",
    "sv": 1,
    "unsupported": [
      {
        "reason": "reaction resistance on attack hit and teleportation with resource tracking",
        "tags": [
          "resource",
          "reaction"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|gunner": {
    "name": "Gunner",
    "sv": 1,
    "unsupported": [
      {
        "reason": "firearm proficiency (not in skill list), conditional ranged-attack advantage (melee-range specific)",
        "tags": [
          "weapons",
          "proficiency-tools",
          "conditional"
        ]
      }
    ]
  },
  "feat|heavy armor master": {
    "name": "Heavy Armor Master",
    "sv": 1,
    "unsupported": [
      {
        "reason": "damage reduction from nonmagical attacks (requires damage-tracking model)",
        "tags": [
          "damage-reduction",
          "conditional-armor"
        ]
      }
    ]
  },
  "feat|infernal constitution": {
    "name": "Infernal Constitution",
    "sv": 1,
    "unsupported": [
      {
        "reason": "damage resistance to cold/poison (not modeled); poison-condition advantage (condition-specific, not ability-based)",
        "tags": [
          "damage-resistance",
          "conditional-save"
        ]
      }
    ]
  },
  "feat|keenness of the stone giant": {
    "name": "Keenness of the Stone Giant",
    "sv": 1,
    "unsupported": [
      {
        "reason": "darkvision (not modeled); spell attacks with resource tracking (requires attacks/spells table and use-pool model)",
        "tags": [
          "spell-attack",
          "resource",
          "feature"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|knight of the crown": {
    "name": "Knight of the Crown",
    "sv": 1,
    "unsupported": [
      {
        "reason": "conditional extra reaction attack on ally with d8 damage roll (requires action/reaction model and resource tracking)",
        "tags": [
          "extra-action",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|knight of the rose": {
    "name": "Knight of the Rose",
    "sv": 1,
    "unsupported": [
      {
        "reason": "grants temporary HP to a chosen creature via a bonus action; no temp-HP target on the sheet",
        "tags": [
          "temp-hp",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|knight of the sword": {
    "name": "Knight of the Sword",
    "sv": 1,
    "unsupported": [
      {
        "reason": "weapon-attack-conditional save DC and frightened/disadvantage effects; needs a condition model and a use pool",
        "tags": [
          "weapon-attack",
          "condition-tracking",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|mage slayer": {
    "name": "Mage Slayer",
    "sv": 1,
    "unsupported": [
      {
        "reason": "proximity-conditional advantage on saves against spells; reaction attack on spell casting; concentration disadvantage",
        "tags": [
          "conditional-advantage",
          "reaction"
        ]
      }
    ]
  },
  "feat|martial adept": {
    "name": "Martial Adept",
    "sv": 1,
    "unsupported": [
      {
        "reason": "maneuvers and superiority die resource pool not modeled",
        "tags": [
          "resource",
          "maneuvers"
        ]
      }
    ]
  },
  "feat|medium armor master": {
    "name": "Medium Armor Master",
    "sv": 1,
    "unsupported": [
      {
        "reason": "AC not modeled; conditional AC bonus and stealth mechanic require AC target",
        "tags": [
          "ac"
        ]
      }
    ]
  },
  "feat|metamagic adept": {
    "name": "Metamagic Adept",
    "sv": 1,
    "unsupported": [
      {
        "reason": "sorcery points resource pool and metamagic options not modeled",
        "tags": [
          "resource"
        ]
      }
    ]
  },
  "feat|mobile": {
    "name": "Mobile",
    "sv": 1,
    "effects": [
      { "target": "speed", "op": "add", "value": 10 }
    ],
    "unsupported": [
      {
        "reason": "no extra Dash movement cost in difficult terrain, and no opportunity-attack immunity after a melee attack",
        "tags": [
          "movement",
          "reaction"
        ]
      }
    ]
  },
  "feat|mounted combatant": {
    "name": "Mounted Combatant",
    "sv": 1,
    "unsupported": [
      {
        "reason": "advantage on attacks conditional on being mounted and target size; mount damage mitigation not modeled",
        "tags": [
          "conditional-advantage",
          "mount"
        ]
      }
    ]
  },
  "feat|orcish fury": {
    "name": "Orcish Fury",
    "sv": 1,
    "unsupported": [
      {
        "reason": "damage reroll (once per short rest) and bonus action attack tied to race-specific trait",
        "tags": [
          "reroll",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "feat|piercer": {
    "name": "Piercer",
    "sv": 1,
    "unsupported": [
      {
        "reason": "once-per-turn damage reroll and extra critical damage die not modeled",
        "tags": [
          "reroll"
        ]
      }
    ]
  },
  "feat|planar wanderer": {
    "name": "Planar Wanderer",
    "sv": 1,
    "unsupported": [
      {
        "reason": "resistance selection (non-persistent state), portal DC checks, and limited-resource detection",
        "tags": [
          "resource",
          "complex-action"
        ]
      }
    ]
  },
  "feat|poisoner": {
    "name": "Poisoner",
    "sv": 1,
    "unsupported": [
      {
        "reason": "poison damage and save DC applied after attack hit; requires attacks/damage roll mechanics",
        "tags": [
          "attack",
          "damage"
        ]
      }
    ]
  },
  "feat|polearm master": {
    "name": "Polearm Master",
    "sv": 1,
    "unsupported": [
      {
        "reason": "bonus action extra attack with weapon; extra attack action mechanics not modeled",
        "tags": [
          "attack",
          "action"
        ]
      }
    ]
  },
  "feat|prodigy": {
    "name": "Prodigy",
    "sv": 1,
    "unsupported": [
      {
        "reason": "expertise application constrained by existing proficiencies (not tracked); tool and language proficiencies out of scope",
        "tags": [
          "expertise",
          "proficiency"
        ]
      }
    ]
  },
  "feat|quicksmithing": {
    "name": "Quicksmithing",
    "sv": 1,
    "unsupported": [
      {
        "reason": "ritual spell learning and mastery, clockwork device creation with resource tracking (3 active at once)",
        "tags": [
          "spell",
          "resource"
        ]
      }
    ]
  },
  "feat|revenant blade": {
    "name": "Revenant Blade",
    "sv": 1,
    "unsupported": [
      {
        "reason": "AC bonus conditional on weapon and grip; AC target not modeled",
        "tags": [
          "ac",
          "weapon"
        ]
      }
    ]
  },
  "feat|righteous heritor": {
    "name": "Righteous Heritor",
    "sv": 1,
    "unsupported": [
      {
        "reason": "reaction damage reduction (1d10 + proficiency bonus) with uses tracking (= proficiency bonus per rest)",
        "tags": [
          "damage",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|rune shaper": {
    "name": "Rune Shaper",
    "sv": 1,
    "unsupported": [
      {
        "reason": "spell slot management, rune inscription and mastery tracking, spellcasting ability choice across features",
        "tags": [
          "spell",
          "resource"
        ]
      }
    ]
  },
  "feat|savage attacker": {
    "name": "Savage Attacker",
    "sv": 1,
    "unsupported": [
      {
        "reason": "once-per-turn reroll of weapon damage dice; requires roll-history model",
        "tags": [
          "reroll",
          "attack"
        ]
      }
    ]
  },
  "feat|scion of the outer planes": {
    "name": "Scion of the Outer Planes",
    "sv": 1,
    "unsupported": [
      {
        "reason": "damage resistance (type chosen per plane); resistance target not modeled. Cantrip learning out of scope",
        "tags": [
          "resistance",
          "spell"
        ]
      }
    ]
  },
  "feat|second chance": {
    "name": "Second Chance",
    "sv": 1,
    "unsupported": [
      {
        "reason": "reaction reroll of attack roll against self (post-hoc, enemy roll); reroll model and rest-based use tracking needed",
        "tags": [
          "reroll",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "feat|sentinel": {
    "name": "Sentinel",
    "sv": 1,
    "unsupported": [
      {
        "reason": "opportunity attacks triggering on reach entry, speed reduction on hit, reaction attack on nearby enemy attack; requires action economy and condition mechanics",
        "tags": [
          "attack",
          "action",
          "condition"
        ]
      }
    ]
  },
  "feat|servo crafting": {
    "name": "Servo Crafting",
    "sv": 1,
    "unsupported": [
      {
        "reason": "ritual familiar (construct), telepathic communication, action economy swap (forgo own attack for servo attack)",
        "tags": [
          "familiar",
          "action"
        ]
      }
    ]
  },
  "feat|skill expert": {
    "name": "Skill Expert",
    "sv": 1,
    "choices": [
      {
        "id": "skillprof",
        "kind": "pick",
        "n": 1,
        "options": [
          "acrobatics",
          "animalhandling",
          "arcana",
          "athletics",
          "deception",
          "history",
          "insight",
          "intimidation",
          "investigation",
          "medicine",
          "nature",
          "perception",
          "performance",
          "persuasion",
          "religion",
          "sleightofhand",
          "stealth",
          "survival"
        ],
        "label": "Gain proficiency in"
      },
      {
        "id": "skillexp",
        "kind": "pick",
        "n": 1,
        "options": [
          "acrobatics",
          "animalhandling",
          "arcana",
          "athletics",
          "deception",
          "history",
          "insight",
          "intimidation",
          "investigation",
          "medicine",
          "nature",
          "perception",
          "performance",
          "persuasion",
          "religion",
          "sleightofhand",
          "stealth",
          "survival"
        ],
        "label": "Gain expertise in"
      }
    ],
    "effects": [
      {
        "target": "skill-{choice:skillprof}",
        "op": "prof",
        "activation": {
          "kind": "choice",
          "choice": "skillprof"
        }
      },
      {
        "target": "skill-{choice:skillexp}",
        "op": "expertise",
        "activation": {
          "kind": "choice",
          "choice": "skillexp"
        }
      }
    ]
  },
  "feat|squat nimbleness": {
    "name": "Squat Nimbleness",
    "sv": 1,
    "choices": [
      {
        "id": "skill",
        "kind": "pick",
        "n": 1,
        "options": [
          "acrobatics",
          "athletics"
        ],
        "label": "Gain proficiency in"
      }
    ],
    "effects": [
      {
        "target": "skill-{choice:skill}",
        "op": "prof",
        "activation": {
          "kind": "choice",
          "choice": "skill"
        }
      }
    ]
  },
  "feat|shield master": {
    "name": "Shield Master",
    "sv": 1,
    "unsupported": [
      {
        "reason": "shield AC bonus to saving throws (needs shield AC tracking); reaction-based damage negation",
        "tags": [
          "shield",
          "reaction",
          "save"
        ]
      }
    ]
  },
  "feat|skilled": {
    "name": "Skilled",
    "sv": 1,
    "unsupported": [
      {
        "reason": "tool proficiencies not modeled (feat allows any combination of three skills or tools)",
        "tags": [
          "tools"
        ]
      }
    ]
  },
  "feat|slasher": {
    "name": "Slasher",
    "sv": 1,
    "unsupported": [
      {
        "reason": "once-per-turn speed reduction and critical-hit rider; needs a condition model and resource tracking",
        "tags": [
          "attack",
          "damage",
          "resource"
        ]
      }
    ]
  },
  "feat|soul of the storm giant": {
    "name": "Soul of the Storm Giant",
    "sv": 1,
    "unsupported": [
      {
        "reason": "bonus-action aura toggle, resistance to damage types, disadvantage on attacks against you, creature saving throws, and resource tracking (uses = prof bonus)",
        "tags": [
          "aura",
          "resistance",
          "save",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|squire of solamnia": {
    "name": "Squire of Solamnia",
    "sv": 1,
    "unsupported": [
      {
        "reason": "once-per-turn attack advantage and d8 damage roll (Precise Strike); needs resource tracking",
        "tags": [
          "attack",
          "damage",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|strike of the giants": {
    "name": "Strike of the Giants",
    "sv": 1,
    "unsupported": [
      {
        "reason": "once-per-turn weapon damage effects with conditional creature saving throws; six strike options; needs a target-save model and resource tracking",
        "tags": [
          "attack",
          "damage",
          "save",
          "resource"
        ]
      }
    ],
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "feat|tavern brawler": {
    "name": "Tavern Brawler",
    "sv": 1,
    "unsupported": [
      {
        "reason": "weapon proficiency, unarmed strike damage and grappling aren't tracked",
        "tags": [
          "weapon",
          "unarmed",
          "grapple"
        ]
      }
    ]
  },
  "feat|telekinetic": {
    "name": "Telekinetic",
    "sv": 1,
    "effects": [
      { "target": "spell-grant", "op": "grant-free", "value": { "name": "mage hand" } }
    ],
    "unsupported": [
      {
        "reason": "needs custom ability-based save DC (shove save = 8 + prof + ability mod)",
        "tags": [
          "spell",
          "save-dc"
        ]
      }
    ]
  },
  "feat|telepathic": {
    "name": "Telepathic",
    "sv": 1,
    "effects": [
      { "target": "spell-grant", "op": "grant-innate", "value": { "name": "detect thoughts" } }
    ],
    "uses": { "max": 1, "per": "lr" },
    "unsupported": [
      {
        "reason": "telepathic communication with any creature you can see within 60 feet — no telepathy/communication model",
        "tags": ["telepathy", "communication"]
      }
    ]
  },
  "feat|vampiric exultation": {
    "name": "Vampiric Exultation",
    "sv": 1,
    "unsupported": [
      {
        "reason": "needs flying speed, duration model, and rest-based resource tracking",
        "tags": [
          "speed",
          "flying",
          "resource",
          "duration"
        ]
      }
    ],
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "feat|vigor of the hill giant": {
    "name": "Vigor of the Hill Giant",
    "sv": 1,
    "unsupported": [
      {
        "reason": "needs reaction mechanics, condition state tracking, and hit-dice resource model",
        "tags": [
          "reaction",
          "condition",
          "resource",
          "hit-dice"
        ]
      }
    ]
  },
  "feat|war caster": {
    "name": "War Caster",
    "sv": 1,
    "unsupported": [
      {
        "reason": "needs concentration-specific save advantage, component tracking, and action economy",
        "tags": [
          "advantage-conditional",
          "concentration",
          "action",
          "spell"
        ]
      }
    ]
  },
  "feat|weapon master": {
    "name": "Weapon Master",
    "sv": 1,
    "unsupported": [
      {
        "reason": "needs weapons/proficiencies table to assign specific weapon proficiencies",
        "tags": [
          "weapon",
          "proficiency"
        ]
      }
    ]
  }
});
