/* ============================================================
   Limited-use trackers for racial traits — generated by
   effects/tools/generate-uses.js (a deterministic scan of data/races.json
   for explicit finite-use + recharge phrasings; see its header comment).
   `uses`-only for now — races have no other effects/db entries yet (full
   race conversion is future work, see DOCS.md); this only restores the
   finite-use pip tracker the app used to derive live from feature text.
   ============================================================ */
registerEffects({
  "race|aasimar|healing hands": {
    "name": "Healing Hands",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "race|astral elf|starlight step": {
    "name": "Starlight Step",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|autognome|built for success": {
    "name": "Built for Success",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|deep gnome|svirfneblin camouflage": {
    "name": "Svirfneblin Camouflage",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|dhampir|vampiric bite": {
    "name": "Vampiric Bite",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|dragonborn (chromatic)|breath weapon": {
    "name": "Breath Weapon",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|dragonborn (gem)|breath weapon": {
    "name": "Breath Weapon",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|dragonborn (metallic)|breath weapon": {
    "name": "Breath Weapon",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|eladrin|fey step": {
    "name": "Fey Step",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|firbolg|hidden step": {
    "name": "Hidden Step",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "race|giff|astral spark": {
    "name": "Astral Spark",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|goblin|fury of the small": {
    "name": "Fury of the Small",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "race|hadozee|hadozee dodge": {
    "name": "Hadozee Dodge",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|harengon|rabbit hop": {
    "name": "Rabbit Hop",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|hobgoblin|saving face": {
    "name": "Saving Face",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "race|kender|taunt": {
    "name": "Taunt",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|kobold|grovel, cower, and beg": {
    "name": "Grovel, Cower, and Beg",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "race|leonin|daunting roar": {
    "name": "Daunting Roar",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "race|reborn|knowledge from a past life": {
    "name": "Knowledge from a Past Life",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|shadar-kai|blessing of the raven queen": {
    "name": "Blessing of the Raven Queen",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|shifter|shifting": {
    "name": "Shifting",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "race|tabaxi|feline agility": {
    "name": "Feline Agility",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "race|tiefling|infernal legacy": {
    "name": "Infernal Legacy",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  }
});
