/* ============================================================
   Limited-use trackers for class/subclass features — generated by
   effects/tools/generate-uses.js (a deterministic scan of data/class/*.json
   for explicit finite-use + recharge phrasings; see its header comment for
   what it catches and deliberately skips, e.g. features whose use-count
   itself scales by level, like Action Surge or Channel Divinity, are left
   out rather than given a flat number that would be wrong at most levels).

   `uses`-only: these are features whose class/subclass has no fuller entry
   in a classes-batch-*.js file yet, so this restores just the finite-use pip
   tracker the app used to derive live from feature text (see
   conversion-guide.md). Any key a converted batch file already defines is
   omitted here on purpose — registerEffects() assigns whole entries, so a
   `uses`-only duplicate would silently erase that batch entry's effects
   rather than merge with them. generate-uses.js skips those keys for you.
   ============================================================ */
registerEffects({
  "class|bard|bardic inspiration": {
    "name": "Bardic Inspiration",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "cha"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|bard|college of eloquence|universal speech": {
    "name": "Universal Speech",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|bard|college of eloquence|infectious inspiration": {
    "name": "Infectious Inspiration",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "cha"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|bard|college of glamour|mantle of majesty": {
    "name": "Mantle of Majesty",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|bard|college of whispers|words of terror": {
    "name": "Words of Terror",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|bard|college of whispers|shadow lore": {
    "name": "Shadow Lore",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|cleric|light domain|warding flare": {
    "name": "Warding Flare",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "wis"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|cleric|grave domain|eyes of the grave": {
    "name": "Eyes of the Grave",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "wis"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|cleric|grave domain|sentinel at death's door": {
    "name": "Sentinel at Death's Door",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "wis"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|druid|circle of stars|cosmic omen": {
    "name": "Cosmic Omen",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|druid|circle of dreams|walker in dreams": {
    "name": "Walker in Dreams",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "sr",
      "delayed": null
    }
  },
  "class|fighter|second wind": {
    "name": "Second Wind",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "sr",
      "delayed": null
    }
  },
  "subclass|fighter|rune knight|runic shield": {
    "name": "Runic Shield",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|fighter|cavalier|unwavering mark": {
    "name": "Unwavering Mark",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "str"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|fighter|cavalier|warding maneuver": {
    "name": "Warding Maneuver",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "con"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "class|mystic|consumptive power": {
    "name": "Consumptive Power",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|mystic|order of the awakened|spectral form": {
    "name": "Spectral Form",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|mystic|order of the nomad|memory of one thousand steps": {
    "name": "Memory of One Thousand Steps",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "class|paladin|cleansing touch": {
    "name": "Cleansing Touch",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "cha"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of the ancients|elder champion": {
    "name": "Elder Champion",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of devotion|holy nimbus": {
    "name": "Holy Nimbus",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of vengeance|avenging angel": {
    "name": "Avenging Angel",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of the crown|exalted champion": {
    "name": "Exalted Champion",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of glory|glorious defense": {
    "name": "Glorious Defense",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "cha"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of glory|living legend": {
    "name": "Living Legend",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of the watchers|mortal bulwark": {
    "name": "Mortal Bulwark",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|paladin|oath of conquest|invincible conqueror": {
    "name": "Invincible Conqueror",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "class|ranger|favored foe": {
    "name": "Favored Foe",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "class|ranger|deft explorer improvement": {
    "name": "Deft Explorer Improvement",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "class|ranger|nature's veil": {
    "name": "Nature's Veil",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|drakewarden|perfected bond": {
    "name": "Perfected Bond",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|fey wanderer|misty wanderer": {
    "name": "Misty Wanderer",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "wis"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|swarmkeeper|writhing tide": {
    "name": "Writhing Tide",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|swarmkeeper|swarming dispersal": {
    "name": "Swarming Dispersal",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|horizon walker|detect portal": {
    "name": "Detect Portal",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|horizon walker|ethereal step": {
    "name": "Ethereal Step",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|monster slayer|hunter's sense": {
    "name": "Hunter's Sense",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "wis"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|ranger|monster slayer|magic-user's nemesis": {
    "name": "Magic-User's Nemesis",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "class|rogue|stroke of luck": {
    "name": "Stroke of Luck",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|rogue|arcane trickster|spell thief": {
    "name": "Spell Thief",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|rogue|phantom|wails from the grave": {
    "name": "Wails from the Grave",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|rogue|inquisitive|unerring eye": {
    "name": "Unerring Eye",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "wis"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|sorcerer|lunar sorcery|lunar boons": {
    "name": "Lunar Boons",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|sorcerer|clockwork soul|restore balance": {
    "name": "Restore Balance",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|sorcerer|clockwork soul|trance of order": {
    "name": "Trance of Order",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|sorcerer|clockwork soul|clockwork cavalcade": {
    "name": "Clockwork Cavalcade",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|sorcerer|divine soul|unearthly recovery": {
    "name": "Unearthly Recovery",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|warlock|the great old one|entropic ward": {
    "name": "Entropic Ward",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|warlock|the undying|indestructible life": {
    "name": "Indestructible Life",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|warlock|the fathomless|tentacle of the deeps": {
    "name": "Tentacle of the Deeps",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|warlock|the fathomless|fathomless plunge": {
    "name": "Fathomless Plunge",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|warlock|the genie|elemental gift": {
    "name": "Elemental Gift",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|warlock|the genie|limited wish": {
    "name": "Limited Wish",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "lr",
      "delayed": {
        "expr": "1d4"
      }
    }
  },
  "subclass|warlock|the undead|form of dread": {
    "name": "Form of Dread",
    "sv": 1,
    "uses": {
      "max": {
        "prof": true
      },
      "per": "lr",
      "delayed": null
    }
  },
  "class|wizard|arcane recovery": {
    "name": "Arcane Recovery",
    "sv": 1,
    "uses": {
      "max": 1,
      "per": "sr",
      "delayed": null
    }
  },
  "subclass|wizard|chronurgy magic|chronal shift": {
    "name": "Chronal Shift",
    "sv": 1,
    "uses": {
      "max": 2,
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|wizard|chronurgy magic|momentary stasis": {
    "name": "Momentary Stasis",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "int"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  },
  "subclass|wizard|graviturgy magic|violent attraction": {
    "name": "Violent Attraction",
    "sv": 1,
    "uses": {
      "max": {
        "max": [
          {
            "mod": "int"
          },
          1
        ]
      },
      "per": "lr",
      "delayed": null
    }
  }
});
