/* Regenerates pmcrwf's icons from icons/icon-source.jpg (a Pallas's cat and her kittens, stacked).
   Run by hand when the icon changes; the outputs are committed, so nobody needs this to use pmcrwf.

     NODE_PATH=<global node_modules> node tools/make-icons.cjs

   Uses the Chromium Playwright already drives for the browser checks, since this project has no
   image library. The source is already square and used whole; a maskable icon keeps its
   subject inside the middle 80% (the part every mask shape leaves), over a blurred copy of itself. */
const fs = require("fs");
const path = require("path");
const { chromium } = require("playwright");

const ICONS = path.join(__dirname, "..", "icons");
const CROP = { x: 0, y: 0, size: 225 };   // the whole 225x225 source

(async () => {
  const browser = await chromium.launch(process.env.PMCRWF_TEST_CHANNEL ? { channel: process.env.PMCRWF_TEST_CHANNEL } : {});
  const page = await browser.newPage();
  const src = "data:image/jpeg;base64," + fs.readFileSync(path.join(ICONS, "icon-source.jpg")).toString("base64");
  const out = await page.evaluate(async ({ src, crop }) => {
    const img = new Image(); img.src = src; await img.decode();
    const render = (size, maskable) => {
      const c = document.createElement("canvas"); c.width = c.height = size;
      const g = c.getContext("2d"); g.imageSmoothingEnabled = true; g.imageSmoothingQuality = "high";
      if (maskable) {
        g.filter = `blur(${size / 24}px)`;
        // Drawn past the canvas edges so the blur's fade-out falls outside it.
        g.drawImage(img, crop.x, crop.y, crop.size, crop.size, -size * .2, -size * .2, size * 1.4, size * 1.4);
        g.filter = "none";
        const inset = size * .1;
        g.drawImage(img, crop.x, crop.y, crop.size, crop.size, inset, inset, size - 2 * inset, size - 2 * inset);
      } else g.drawImage(img, crop.x, crop.y, crop.size, crop.size, 0, 0, size, size);
      return c.toDataURL("image/png");
    };
    return { i192: render(192), i512: render(512), mask: render(512, true), i64: render(64) };
  }, { src, crop: CROP });
  const png = u => Buffer.from(u.split(",")[1], "base64");
  fs.writeFileSync(path.join(ICONS, "icon-192.png"), png(out.i192));
  fs.writeFileSync(path.join(ICONS, "icon-512.png"), png(out.i512));
  fs.writeFileSync(path.join(ICONS, "icon-maskable-512.png"), png(out.mask));
  // The favicon stays an SVG so every existing reference to icons/icon.svg keeps working.
  fs.writeFileSync(path.join(ICONS, "icon.svg"),
    `<!-- pmcrwf's icon, generated by tools/make-icons.cjs from icons/icon-source.jpg. -->\n` +
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 64 64" width="64" height="64">` +
    `<image width="64" height="64" href="${out.i64}" xlink:href="${out.i64}"/></svg>\n`);
  await browser.close();
  console.log("Wrote icon-192.png, icon-512.png, icon-maskable-512.png and icon.svg.");
})().catch(e => { console.error(e); process.exitCode = 1; });
