/* ============================================================
   COMBOBOX — a text box you can type in, with a dropdown arrow that opens
   the full list, and a list that filters live as you type.

   Why this exists rather than a <select> or an <input list>:

   - A <select> can't be typed into, and these lists are long (ninety-odd
     races, sixty-odd backgrounds). Scrolling to "Yuan-ti Pureblood" is
     worse than typing three letters.
   - An <input list="…"> (native datalist) *does* filter as you type, but
     it gives no affordance that a list exists at all — no arrow — and
     browsers disagree about whether clicking the field opens it. That was
     the complaint this replaces.
   - Free text has to keep working. Every list here comes from user-supplied
     data (see DOCS' "Where game data comes from") that may be absent
     entirely, so the list is a convenience and never a gate: whatever you
     type is the value, whether or not it's in the list.

   USAGE — markup is generated by comboboxHtml(), then behaviour is attached
   by initComboboxes(container) after that markup is in the DOM:

       html += comboboxHtml({ id: "cr-race", value: c.race, options: races,
                              placeholder: "type to search", width: "12rem" });
       …
       initComboboxes($("cr-body"));

   The input fires ordinary `input` and `change` events, so callers wire it
   up exactly like a plain text box and nothing here needs to know about
   them. Picking from the list dispatches `input` too, so a caller that only
   listens for `input` still sees the pick.

   RE-RENDERING. The panel lives in the document, not inside the input's own
   subtree, so a caller that redraws its body on `input` (the character
   creator does, to refresh what the race implies) will destroy the panel.
   That's why the open panel is tracked globally and reattached on demand:
   see comboReopen(). A caller that redraws must call initComboboxes() again,
   which restores the panel for whichever field still holds focus.
   ============================================================ */

let COMBO_OPEN = null;      // { input, panel, options, highlight }

/* Attribute-safe escaping. escapeHtml() (spell-library.js) handles & < > but NOT the double quote,
   because everywhere else it's used the result goes in element text. Here it goes in an attribute
   value, and an unescaped quote inside JSON ends the attribute early — which silently emptied every
   option list. Kept local rather than changing escapeHtml, whose callers all rely on its behaviour. */
function comboAttr(s) { return escapeHtml(s).replace(/"/g, "&quot;"); }

function comboboxHtml(o) {
  const opts = (o.options || []).map(x => String(x));
  // Options ride along in the markup rather than in a side registry, so a caller that re-renders can
  // never leave the widget pointing at a stale list.
  const dataOpts = comboAttr(JSON.stringify(opts));
  const cls = ["combo-input", o.extraClass || ""].filter(Boolean).join(" ");
  const attrs = [
    o.id ? `id="${o.id}"` : "",
    o.dataAttr ? o.dataAttr : "",
    // House-rule bans (src/house-rules.js). Declared once in markup; the panel reads it back off the
    // input, so a banned option colours red rather than disappearing from the list.
    o.banKind ? `data-ban-kind="${comboAttr(o.banKind)}"` : "",
    o.banPrefix ? `data-ban-prefix="${comboAttr(o.banPrefix)}"` : "",
  ].filter(Boolean).join(" ");
  return `<span class="combo" style="width:${o.width || "12rem"}">` +
    `<input type="text" class="${cls}" ${attrs} value="${comboAttr(o.value || "")}"` +
      ` placeholder="${comboAttr(o.placeholder || "")}" autocomplete="off" data-combo-options="${dataOpts}">` +
    `<button type="button" class="combo-arrow" tabindex="-1" title="show all options">&#9662;</button>` +
    `</span>`;
}

function comboOptionsOf(input) {
  try { return JSON.parse(input.dataset.comboOptions || "[]"); } catch (e) { return []; }
}

/* Matching is "contains", not "starts with": people look for "Half-Elf" by typing "elf", and for
   "Xanathar's Guide" by typing "xanathar". An empty box shows everything, which is what the arrow
   is for. */
function comboMatches(input, q) {
  const all = comboOptionsOf(input);
  const needle = (q || "").trim().toLowerCase();
  if (!needle) return all;
  const starts = [], contains = [];
  all.forEach(o => {
    const l = o.toLowerCase();
    if (l.startsWith(needle)) starts.push(o);
    else if (l.includes(needle)) contains.push(o);
  });
  return starts.concat(contains);   // prefix matches first — "elf" should offer Elf before Half-Elf
}

function comboClose() {
  if (!COMBO_OPEN) return;
  if (COMBO_OPEN.panel && COMBO_OPEN.panel.parentNode) COMBO_OPEN.panel.remove();
  COMBO_OPEN = null;
}

function comboPanelHtml(options, highlight, query, input) {
  if (!options.length) {
    return `<div class="combo-empty hint">${query ? "no match — what you typed is kept as-is" : "no options loaded"}</div>`;
  }
  // A banned option is still listed and still pickable — it just says so. See house-rules.js for why
  // marking beats removing.
  const ban = (typeof banInfoOf === "function") ? banInfoOf(input) : null;
  return options.map((o, i) => {
    const banned = ban && typeof isBannedOption === "function" && isBannedOption(ban.kind, o, ban.prefix);
    return `<div class="combo-opt${i === highlight ? " hl" : ""}${banned ? " banned-opt" : ""}" data-comboidx="${i}"` +
      `${banned ? ` title="banned by house rule"` : ""}>${escapeHtml(o)}${banned ? ` <span class="banned-flag">banned</span>` : ""}</div>`;
  }).join("");
}

/* Position the panel under its input. Fixed positioning, because the sheet's modules are absolutely
   positioned and can be scrolled or clipped (see layout.js) — a panel positioned inside one would be
   cut off by its module's overflow. */
function comboPlace(input, panel) {
  const r = input.getBoundingClientRect();
  panel.style.left = r.left + "px";
  panel.style.top = (r.bottom + 1) + "px";
  panel.style.minWidth = r.width + "px";
  // Flip above when there isn't room below, so the last field in a dialog is still usable.
  const room = window.innerHeight - r.bottom;
  if (room < 160 && r.top > room) {
    panel.style.top = "";
    panel.style.bottom = (window.innerHeight - r.top + 1) + "px";
  } else {
    panel.style.bottom = "";
  }
}

function comboOpen(input, opts) {
  const options = opts || comboMatches(input, input.value);
  if (COMBO_OPEN && COMBO_OPEN.input === input) {
    COMBO_OPEN.options = options;
    COMBO_OPEN.highlight = Math.min(COMBO_OPEN.highlight, options.length - 1);
    COMBO_OPEN.panel.innerHTML = comboPanelHtml(options, COMBO_OPEN.highlight, input.value, input);
    comboPlace(input, COMBO_OPEN.panel);
    return;
  }
  comboClose();
  const panel = document.createElement("div");
  panel.className = "combo-panel";
  panel.innerHTML = comboPanelHtml(options, -1, input.value, input);
  document.body.appendChild(panel);
  comboPlace(input, panel);
  COMBO_OPEN = { input, panel, options, highlight: -1 };
}

function comboPick(value) {
  if (!COMBO_OPEN) return;
  const input = COMBO_OPEN.input;
  input.value = value;
  comboClose();
  // Callers listen for `input` (see this file's header) — dispatch it so picking behaves exactly
  // like typing the value out in full.
  input.dispatchEvent(new Event("input", { bubbles: true }));
  input.dispatchEvent(new Event("change", { bubbles: true }));
  input.focus();
}

function comboHighlight(delta) {
  if (!COMBO_OPEN || !COMBO_OPEN.options.length) return;
  const n = COMBO_OPEN.options.length;
  let h = COMBO_OPEN.highlight + delta;
  if (h < 0) h = n - 1; else if (h >= n) h = 0;
  COMBO_OPEN.highlight = h;
  COMBO_OPEN.panel.innerHTML = comboPanelHtml(COMBO_OPEN.options, h, COMBO_OPEN.input.value, COMBO_OPEN.input);
  const el = COMBO_OPEN.panel.querySelector(".combo-opt.hl");
  if (el && el.scrollIntoView) el.scrollIntoView({ block: "nearest" });
}

/* Reopen the panel for whichever combobox currently has focus. Called after a caller re-renders its
   body: the input is a brand-new element by then, so the old panel (and the old COMBO_OPEN.input
   reference) are stale. Without this, typing in a combobox inside the character creator would show
   the list for exactly one keystroke. */
function comboReopen() {
  const el = document.activeElement;
  if (!el || !el.classList || !el.classList.contains("combo-input")) { comboClose(); return; }
  comboOpen(el);
}

/* Attach behaviour to any combobox markup inside `root` that hasn't got it yet, and restore the open
   panel if one of them is focused. Safe to call repeatedly — that's the point. */
function initComboboxes(root) {
  (root || document).querySelectorAll(".combo-input").forEach(inp => {
    if (inp.dataset.comboReady) return;
    inp.dataset.comboReady = "1";
    inp.addEventListener("focus", () => comboOpen(inp));
    inp.addEventListener("blur", () => {
      // Deferred for two reasons: a click on an option fires blur before the click handler (closing
      // now would remove the option from under the pointer), and a caller that re-renders on `input`
      // detaches this element mid-keystroke, which also fires blur. So the test is "is a combobox
      // still focused?" rather than "is it still THIS one?" — after a re-render it never is.
      setTimeout(() => {
        const a = document.activeElement;
        if (a && a.classList && a.classList.contains("combo-input")) return;
        comboClose();
      }, 120);
    });
  });
  // A freshly rendered combobox holding a banned value should already be red, before it's touched.
  if (typeof markBannedInputs === "function") markBannedInputs(root);
  comboReopen();
}

document.addEventListener("DOMContentLoaded", () => {
  // Typing: refilter. This listener is on the document so it survives any amount of re-rendering by
  // whoever owns the field.
  document.addEventListener("input", e => {
    const inp = e.target.closest && e.target.closest(".combo-input");
    if (!inp) return;
    /* Deferred a frame, because a caller may re-render inside its OWN input handler — which runs
       first, since it's bound closer to the target — replacing this very element. Acting on `inp`
       directly would then open a panel anchored to a node no longer in the document. Resolving
       against whatever ends up focused survives that; falling back to `inp` covers a combobox nobody
       re-renders. */
    requestAnimationFrame(() => {
      const live = document.activeElement;
      const target = (live && live.classList && live.classList.contains("combo-input")) ? live
                   : (document.contains(inp) ? inp : null);
      if (target) comboOpen(target, comboMatches(target, target.value));
    });
  });

  document.addEventListener("click", e => {
    const arrow = e.target.closest(".combo-arrow");
    if (arrow) {
      e.preventDefault();
      const inp = arrow.parentNode.querySelector(".combo-input");
      // The arrow always offers the WHOLE list, not the filtered one: it is the "show me everything"
      // affordance, and filtering it by leftover text would make it useless after a failed search.
      if (COMBO_OPEN && COMBO_OPEN.input === inp) comboClose();
      else { inp.focus(); comboOpen(inp, comboOptionsOf(inp)); }
      return;
    }
    const opt = e.target.closest(".combo-opt");
    if (opt && COMBO_OPEN) { comboPick(COMBO_OPEN.options[Number(opt.dataset.comboidx)]); return; }
    if (!e.target.closest(".combo")) comboClose();
  });

  document.addEventListener("keydown", e => {
    if (!COMBO_OPEN || e.target !== COMBO_OPEN.input) return;
    if (e.key === "ArrowDown") { e.preventDefault(); comboHighlight(1); return; }
    if (e.key === "ArrowUp") { e.preventDefault(); comboHighlight(-1); return; }
    if (e.key === "Enter") {
      if (COMBO_OPEN.highlight >= 0) { e.preventDefault(); comboPick(COMBO_OPEN.options[COMBO_OPEN.highlight]); }
      else comboClose();
      return;
    }
    // Esc closes the list without disturbing the value — and stops there, so it doesn't also close
    // the dialog the combobox is sitting in.
    if (e.key === "Escape") { e.stopPropagation(); comboClose(); return; }
    if (e.key === "Tab") comboClose();
  });

  // The panel is positioned in viewport coordinates, so anything that moves the input invalidates it.
  window.addEventListener("resize", comboClose);
  window.addEventListener("scroll", () => { if (COMBO_OPEN) comboPlace(COMBO_OPEN.input, COMBO_OPEN.panel); }, true);
});
